apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: monitoring
  labels:
    release: monitoring   # имя релиза kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api            # эти метки должны быть на Service твоего API
  namespaceSelector:
    any: true             # или перечисли нужные namespaces через matchNames
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: worker
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
