global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']   # твой API должен отдавать /metrics
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8080'] # если у воркера есть /metrics; либо вообще убери
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
